/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poscnsl2;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Butaw
 */
public class LoginSystem extends javax.swing.JFrame {

    /**
     * @return the mod
     */
    public String getMod() {
        return mod;
    }

    /**
     * @param mod the mod to set
     */
    public void setMod(String mod) {
        this.mod = mod;
    }

    /**
     * Creates new form LoginSystem
     */
    static Connection con = My_Connection.dbConnection();
    protected String mod = "Seller";

    public LoginSystem() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        remove(createPanel);
        repaint();
        revalidate();
        add(loginPanel);
        repaint();
        revalidate();
        lblInvalid.hide();
        lblcapsWarning.hide();

    }

    public void clear() {
        tfCreateUser.setText("");
        tfName.setText("");
        pfConfirm.setText("");
        pfPass.setText("");
        tfUser.setText("");
        pfCreatePass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        bLogin = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        lblInvalid = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        lblcapsWarning = new javax.swing.JLabel();
        createPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bCreate = new javax.swing.JButton();
        tfCreateUser = new javax.swing.JTextField();
        pfCreatePass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pfConfirm = new javax.swing.JPasswordField();
        tfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bLogin.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        loginPanel.add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, 33));

        lblCreate.setBackground(new java.awt.Color(255, 255, 255));
        lblCreate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(51, 51, 255));
        lblCreate.setText("Create an Account(Seller)");
        lblCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCreateMouseExited(evt);
            }
        });
        loginPanel.add(lblCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Username:");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Password:");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 30));

        tfUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginPanel.add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 30));

        lblInvalid.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblInvalid.setForeground(new java.awt.Color(255, 51, 51));
        lblInvalid.setText("Incorrect! Check Username and Password");
        loginPanel.add(lblInvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pfPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        pfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPassFocusLost(evt);
            }
        });
        pfPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfPassMouseClicked(evt);
            }
        });
        pfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfPassKeyReleased(evt);
            }
        });
        loginPanel.add(pfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 30));

        lblcapsWarning.setText("Caps Lock On ⚠");
        loginPanel.add(lblcapsWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 120, 30));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Password:");

        bCreate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bCreate.setText("Create Account");
        bCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateActionPerformed(evt);
            }
        });

        tfCreateUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        pfCreatePass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setText("   Back");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Confirm Password:");

        pfConfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        tfName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Name:");

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCreate)
                            .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfName)
                                .addComponent(pfCreatePass)
                                .addComponent(tfCreateUser)
                                .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfCreatePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        PreparedStatement pst;
        ResultSet rs;
        String confirm = String.valueOf(pfConfirm.getPassword());
        String cPass = String.valueOf(pfCreatePass.getPassword());
        if (tfName.getText().equals("") || tfCreateUser.getText().equals("") || confirm.equals("")
                || cPass.equals("")) { // input fields
            JOptionPane.showMessageDialog(null, "Please input");
        } else {
            if (confirm.equals(cPass)) {//password confirm
                if (!checkuser(tfCreateUser.getText()))// check on db if user exist if not then proceed
                    try {
                    String query = "Insert into userLogin(Name,uPos,uName,uPass)values(?,?,?,?)";
                    pst = con.prepareStatement(query);
                    pst.setString(1, tfName.getText());
                    pst.setString(2, getMod());
                    pst.setString(3, tfCreateUser.getText());
                    pst.setString(4, cPass);
                    pst.execute();
                    pst.close();
                    JOptionPane.showMessageDialog(null, "Created Successfully!");
                    clear();
                    remove(createPanel);
                    repaint();
                    revalidate();
                    add(loginPanel);
                    repaint();
                    revalidate();
                    lblInvalid.hide();
                    lblCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Password not same");

            }
        }

    }//GEN-LAST:event_bCreateActionPerformed

    public boolean checkuser(String input) {
        PreparedStatement pst;
        ResultSet rs;
        boolean user_exist = false;

        String query = "SELECT * FROM `userLogin` WHERE `uName` = ?";

        try {
            pst = con.prepareStatement(query);
            pst.setString(1, input);
            rs = pst.executeQuery();

            if (rs.next()) {
                user_exist = true;
                JOptionPane.showMessageDialog(null, "Username Already Exist", "Username Failed", 2);

            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
        return user_exist;
    }
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        remove(createPanel);
        repaint();
        revalidate();
        add(loginPanel);
        repaint();
        revalidate();
        lblInvalid.hide();
        lblCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jLabel7MouseClicked

    private void lblCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseClicked
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        remove(loginPanel);
        repaint();
        revalidate();
        add(createPanel);
        repaint();
        revalidate();

    }//GEN-LAST:event_lblCreateMouseClicked

    private void lblCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseEntered
        lblCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_lblCreateMouseEntered

    private void lblCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseExited
        lblCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_lblCreateMouseExited

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        PreparedStatement pst;
        String pos, user;

        ResultSet rs;
        if (tfUser.getText().equals("") || pfPass.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "Please input");
        } else {
            try {
                String userLowletter = tfUser.getText().toLowerCase();
                String query = "Select * from userLogin where uName=? and uPass=?";
                pst = con.prepareStatement(query);
                pst.setString(1, userLowletter);
                pst.setString(2, String.valueOf(pfPass.getPassword()));
                rs = pst.executeQuery();
                pos = rs.getString("ID");
                user = rs.getString("Name");
                System.out.println(pos);
                checkPos(pos);
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Wrong User and Pass");
                //JOptionPane.showMessageDialog(null, e);
                lblInvalid.show();
            }
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void pfPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPassKeyReleased
        // TODO add your handling code here:
        capsLock();
    }//GEN-LAST:event_pfPassKeyReleased

    private void pfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPassFocusLost
        // TODO add your handling code here:
        lblcapsWarning.hide();
    }//GEN-LAST:event_pfPassFocusLost

    private void pfPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPassFocusGained
        // TODO add your handling code here:
        capsLock();
    }//GEN-LAST:event_pfPassFocusGained

    private void pfPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPassMouseClicked
        capsLock();
    }//GEN-LAST:event_pfPassMouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_jLabel7MouseExited
    private void capsLock() {
        boolean isOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (isOn == true) {
            lblcapsWarning.show();
        } else {
            lblcapsWarning.hide();
        }
    }

    public boolean checkPos(String input) {
        PreparedStatement pst;
        ResultSet rs;
        String pos, user, uID;
        mainFrame form = new mainFrame();
        boolean user_exist = false;
        String query = "SELECT * FROM `userLogin` WHERE `ID` = ?";

        try {
            pst = con.prepareStatement(query);
            pst.setString(1, input);
            rs = pst.executeQuery();

            if (rs.next()) {
                user_exist = true;
                uID = rs.getString("ID");
                user = rs.getString("Name");
                pos = rs.getString("uPos");
                if (input.equals(uID)) {
                    if (pos.equals("Admin")) {
                        System.out.println("WOOOOOOW you're an admin");
                        form.test(user);
                    } else {
                        System.out.println("WOOOOOOW you're an seller");
                        form.seller();
                        form.test(user);

                    }
                }
                JOptionPane.showMessageDialog(null, "Activated!");
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                this.dispose();

                //JOptionPane.showMessageDialog(null,"Invalid email and pass","Login Error",2 );
            }
            lblInvalid.show();

        } catch (SQLException ex) {
            Logger.getLogger(LoginSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
        return user_exist;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bLogin;
    private javax.swing.JPanel createPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblInvalid;
    private javax.swing.JLabel lblcapsWarning;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField pfConfirm;
    private javax.swing.JPasswordField pfCreatePass;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfCreateUser;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
