/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poscnsl2;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.border.BevelBorder;
import static poscnsl2.POSCnsl.panelChanger;
import static poscnsl2.POSCnsl.aesthetic;

/**
 *
 * @author Butaw
 */
public final class LoginSystem extends javax.swing.JFrame {

    //   static final Connection con = My_Connection.dbConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    protected final String mod = "Seller";
    LoginEvents logEvt;

    private static final LoginSystem login = new LoginSystem();

    private LoginSystem() {
        initComponents();
        logEvt = LoginEvents.getInstance();
        setResizable(false);
        setLocationRelativeTo(null);
        panelChanger(mainPanel, loginPanel);
        // Encrypt("admin");

    }

    public static LoginSystem getInstance() {
        return login;
    }

    public void clear() {
        tfCreateUser.setText("");
        tfName.setText("");
        pfConfirm.setText("");
        pfPass.setText("");
        tfUser.setText("");
        pfCreatePass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        createPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bCreate = new javax.swing.JButton();
        tfCreateUser = new javax.swing.JTextField();
        pfCreatePass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pfConfirm = new javax.swing.JPasswordField();
        tfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        bLogin = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        lblInvalid = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        lblcapsWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        createPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Password:");

        bCreate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bCreate.setText("Create Account");
        bCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateActionPerformed(evt);
            }
        });

        tfCreateUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        pfCreatePass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setText("   Back");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Confirm Password:");

        pfConfirm.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        tfName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Name:");

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCreate)
                            .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfName)
                                .addComponent(pfCreatePass)
                                .addComponent(tfCreateUser)
                                .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfCreatePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(createPanel, "card3");

        loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bLogin.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        bLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserKeyPressed(evt);
            }
        });
        loginPanel.add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, 33));

        lblCreate.setBackground(new java.awt.Color(255, 255, 255));
        lblCreate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(51, 51, 255));
        lblCreate.setText("Create an Account(Seller)");
        lblCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCreateMouseExited(evt);
            }
        });
        loginPanel.add(lblCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Username:");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 80, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Password:");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 80, 30));

        tfUser.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserKeyPressed(evt);
            }
        });
        loginPanel.add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, 30));

        lblInvalid.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblInvalid.setForeground(new java.awt.Color(255, 51, 51));
        loginPanel.add(lblInvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 380, 20));

        pfPass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        pfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPassFocusLost(evt);
            }
        });
        pfPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfPassMouseClicked(evt);
            }
        });
        pfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfPassKeyReleased(evt);
            }
        });
        loginPanel.add(pfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 120, 30));
        loginPanel.add(lblcapsWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 120, 30));

        mainPanel.add(loginPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        /*Create user button */
        String confirm = String.valueOf(pfConfirm.getPassword());
        String cPass = String.valueOf(pfCreatePass.getPassword());
        if (tfName.getText().equals("") || tfCreateUser.getText().equals("") || confirm.equals("")// checking textfields if null or ""
                || cPass.equals("")) { // input fields
            JOptionPane.showMessageDialog(null, "Please input");
        } else {
            if (confirm.equals(cPass)) {//password confirm
                displayCreate();
                logEvt.createAccount();
                clear();
                panelChanger(mainPanel, loginPanel);
            } else {
                JOptionPane.showMessageDialog(null, "Not Same Password");
            }
        }

    }//GEN-LAST:event_bCreateActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        panelChanger(mainPanel, loginPanel);
        lblCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        clear();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void lblCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseClicked
        aesthetic(jLabel7, BevelBorder.RAISED, Color.black);
        panelChanger(mainPanel, createPanel);


    }//GEN-LAST:event_lblCreateMouseClicked

    private void lblCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseEntered
        lblCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_lblCreateMouseEntered

    private void lblCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseExited
        lblCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_lblCreateMouseExited

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        /*login button*/
        if (tfUser.getText().equals("") || pfPass.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "Please input"); // checking fields if it's null or not
        } else {
            displayLogin();
            logEvt.loginAction();
            lblInvalid.setText(logEvt.getWarnMessage());
            checkerWin();
        }
    }//GEN-LAST:event_bLoginActionPerformed
    private void displayLogin() {
        logEvt.setUserName(tfUser.getText().toLowerCase());
        logEvt.setPassword(Encrypt(String.valueOf(pfPass.getPassword())));
        lblInvalid.setText(logEvt.getWarnMessage());
    }

    private void displayCreate() {
        logEvt.setName(tfName.getText());
        logEvt.setUserName(tfCreateUser.getText());
        logEvt.setConfirmPassword(pfConfirm.getText());
        logEvt.setPassword(Encrypt(String.valueOf(pfCreatePass.getPassword())));
    }

    private void pfPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPassKeyReleased
        // TODO add your handling code here:
        capsLock();
    }//GEN-LAST:event_pfPassKeyReleased

    private void pfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPassFocusLost
        // TODO add your handling code here:
        lblcapsWarning.setText("");
    }//GEN-LAST:event_pfPassFocusLost

    private void pfPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPassFocusGained
        // TODO add your handling code here:
        capsLock();
    }//GEN-LAST:event_pfPassFocusGained

    private void pfPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPassMouseClicked
        capsLock();
    }//GEN-LAST:event_pfPassMouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        aesthetic(jLabel7, BevelBorder.LOWERED, Color.red);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        aesthetic(jLabel7, BevelBorder.RAISED, Color.black);
    }//GEN-LAST:event_jLabel7MouseExited

    private void tfUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserKeyPressed
        // TODO add your handling code here:
        enterButton(evt);
    }//GEN-LAST:event_tfUserKeyPressed
    private void enterButton(KeyEvent evt) {
        // boolean isOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_ENTER);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            displayLogin();
            logEvt.loginAction();
            checkerWin();
            lblInvalid.setText(logEvt.getWarnMessage());
        }
    }

    public void clearLogin() {
        tfUser.setText("");
        pfPass.setText("");
    }

    private void checkerWin() {
        mainFrame frame = mainFrame.getInstance();
        if (frame.isShowing()) {
            dispose();
        }
    }

    private void capsLock() {
        boolean isOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (isOn == true) {
            lblcapsWarning.setText("Caps Lock On ⚠");
        } else {
            lblcapsWarning.setText("");
        }
    }

    private String Encrypt(String value) {
        char[] chars = value.toCharArray();
        for (char c : chars) {
            c -= 10;
            value = String.valueOf(c);
            // System.out.print(value);
        }
        return value;
    }

    private String Decrypt(String value) {
        char[] chars = value.toCharArray();
        for (char c : chars) {
            c += 10;
            value = String.valueOf(c);
            //    System.out.print(value);
        }
        return value;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginSystem().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bLogin;
    private javax.swing.JPanel createPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblInvalid;
    private javax.swing.JLabel lblcapsWarning;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField pfConfirm;
    private javax.swing.JPasswordField pfCreatePass;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfCreateUser;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables

}
